menu:
 - url: /
   name: Главная
 - url: /news/
   name: Новости
 - url: /gallery/
   name: Галлерея
 - url: /contacts/
   name: Контакты
 - url: /information/
   name: Сведения об образовательной организации
   submenu:
     - url: #
       name: Основные сведения
     - url: #
       name: Структура и органы управления
     - url: #
       name: Документы
     - url: #
       name: Руководство. Педагогический состав
     - url: #
       name: Образовательные стандарты
     - url: #
       name: График работы
     - url: #
       name: Меры социальной поддержки
     - url: #
       name: Платные услуги

exclude:
 - package.json
 - gulpfile.js
 - node_modules
 - scss
